services:
  app:
    image: shindouhiro/asset-nexus:latest
    container_name: asset-nexus
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/packages/db/sqlite.db
      - NUXT_SESSION_PASSWORD=${NUXT_SESSION_PASSWORD}
      - NUXT_QINIU_ACCESS_KEY=${QINIU_ACCESS_KEY}
      - NUXT_QINIU_SECRET_KEY=${QINIU_SECRET_KEY}
      - NUXT_QINIU_BUCKET=${QINIU_BUCKET}
      - NUXT_QINIU_DOMAIN=${QINIU_DOMAIN}
      - NUXT_PUBLIC_QINIU_BUCKET=${QINIU_BUCKET}
      - NUXT_PUBLIC_QINIU_DOMAIN=${QINIU_DOMAIN}
      - NUXT_PUBLIC_QINIU_REGION=${QINIU_REGION}
    volumes:
      - db-data:/app/packages/db # 使用具名卷，确保镜像内的初始数据库文件能同步到卷中
    restart: always

volumes:
  db-data: # 定义持久化卷

networks:
  default:
    name: asset-nexus-network
